name: star-fleet # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Star Fleet Commander
summary: Build your fleet and battle!
description: Assemble spacecraft, lead battles, and conquer stellar territories in intense space warfare.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  star-fleet:
    command: bin/star-fleet-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  star-fleet:
    plugin: dump
    source: .
    organize:
      star-fleet-bin: bin/
